### ISSUE TITLE
A high score list

### ISSUE THREAD

**Issue by hauxir** [hauxir/haskell-tetris#1]
A high score list would be cool to have on the menu screen, could be stored in a simple plaintext file

**Comment by gregJohnRob** [comment]
Is this still open to be done? :)

**Comment by hauxir** [comment]
yeah, it's not been done yet :)

**Comment by gregJohnRob** [comment]
Mind if I have a crack at it? I am doing Hacktober and learning Haskell and want to kill two birds with one stone.

**Comment by hauxir** [comment]
of course! if you manage to do it I'll merge it to master :)

**Comment by gregJohnRob** [comment]
So far I have a couple functions for reading in a high scores file and converting it into an array of scores which are (String, Int) types :P It did not take 7 hours, although did take longer than I thought it would as Haskell was complaining about my alignment :( 
I was thinking on having the scores in the form "01" 12342 for the first place with a score of 12342, is that okay?

**Comment by hauxir** [comment]
yeah that sounds reasonable. maybe show the top 5 or so in the main menu and an option to view more by pressing a key?

**Comment by gregJohnRob** [comment]
Sure :)

**Comment by hauxir** [comment]
Any news on this?

**Comment by gregJohnRob** [comment]
Sorry, I had tried but I've so far had no luck. I have a friend who does Haskell a lot and has much more experience than me so I am going to ask him. If I don't put in a pull request by the end of the week assume that I can't do it. 
I will say though that it was really cool to see a "big" Haskell program :)

**Comment by hauxir** [comment]
Alright no worries, just curious. I like that you say that it's big, it was made during one week for a university project lol.
